name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # You can specify the version of Node.js you want here

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run test

